### PR TITLE
Add UI for local layer widget

### PR DESCRIPTION
**Pull request by rscheitlin**

### CODE REVIEW

**Comment by rscheitlin** [comment]
Adam, I have made many changes to the widget as well as adding the UI. Contact me with any questions. Robert

**Comment by cmndrbensisko** [comment]
This is a great, incredibly thorough job, Robert.  I've just looked at it briefly, but I'll play around with it in the next few days to verify everything before merging.

One thing I've been mulling over was the "this._viewerMap" reference that we need to keep grabbing to add layers to the map.  Since it's an internal variable, I'd hate for it to move or be renamed in a future iteration of the WAB.  Maybe a good enhancement, or at least one that would save you and I some future headache, would be assigning the map reference into one of our own variables once at Widget startup, and then referencing our own variable throughout the code.  That way, should the WAB code change and "this._viewerMap" moves or is renamed, we only need to change the reference once.

Thanks again for providing this addition for the tool; I'm sure it will see a lot of use by the community.

**Comment by rscheitlin** [comment]
Adam,  Switching to a global map var is solid idea. Not sure if you noticed yet or not but I switched both dynamic and feature types to use PopupTemplate as the maps infoWindow is by default a PopUp dijit.

I would suggest editing the readme concerning the widgets installation to include setting the widgets visibility to false, that way when some one starts WAB and has your widget installed they can choose to turn it on for that particular app or not.

``` JSON
"widgetOnScreen": {
        "widgets": [
            {
                "uri": "widgets/LocalLayerWidget/Widget",
                "vesrion": 1.2,
                "visible": false
            }
        ]
    }
```

I noticed that Stephen Lead submitted a pull request that would add ArcGISTiledMapServer type to the list. I had been considering that but wanted to get this out for people to start using before I spent more time developing another GUI interface for another layer type.

**Comment by cmndrbensisko** [comment]
Awesome improvement RE: the PopUp dijit; I was thinking that the two-template route I had before seemed overcomplicated.  I look forward to rolling this out.

**Comment by cmndrbensisko** [comment]
Hey Robert, hope things are well.  I've started to play around with your pull request, but have been noticing some odd behavior.  When I define my own Dynamic Layers through the settings menu, no popups will appear for the layer on mapclick.  Do you run into this on your end?

I'm running on a Chrome browser, and consuming the following service from a 10.05 server:
http://maps.ottawa.ca/ArcGIS/rest/services/Census_Boundaries/MapServer

I'm not able to successfully define a new Basemap layer using the settings menu either; When I add a new Basemap Layer via the "Edit Basemap Layers" menu and click OK, the OK button on the "Add Basemap" screen remains grayed out.  I'm not able to get past this menu dialog.

I have a feeling I'm missing something obvious here, but any information you can provide would be appreciated.

**Comment by wspiking** [comment]
Hi Adam, I'm running server 10.05 and 10.1 if you need someone to do some additional testing. 
Thanks!
Bill

**Comment by rscheitlin** [comment]
Adam,

   I am looking into the popup issue with that layer, but I am wondering if it is related to another issue with the layer not respecting when a sublayer is turned off or not (this is the issue that someone brought up earlier).

The adding a basemap layer thing is that the ServiceURL dijit will not verify the url until it loses focus (switching to another field or control).

Robert

**Comment by rscheitlin** [comment]
Adam,

   Actually, I got the popups to work for this layer once I understood which sublayers were which in the map service. So what does your json look like that is not working for you?

**Comment by cmndrbensisko** [comment]
It's strange, the JSON looks fine:
```javascript
{
  "layers": {
    "layer": [
      {
        "type": "Dynamic",
        "name": "ffd",
        "url": "http://maps.ottawa.ca/ArcGIS/rest/services/Census_Boundaries/MapServer",
        "opacity": 1,
        "visible": true,
        "imageformat": "png8",
        "popup": {
          "infoTemplates": [
            {
              "layerId": 1,
              "title": "Test",
              "fieldInfos": [
                {
                  "fieldName": "OBJECTID",
                  "label": "OBJECTID",
                  "visible": true
                },
                {
                  "fieldName": "DBUID",
                  "label": "DBUID",
                  "visible": true
                },
                {
                  "fieldName": "DAUID",
                  "label": "DAUID",
                  "visible": true
                }
              ],
              "showAttachments": false
            },
            {
              "layerId": 2,
              "title": "Test",
              "fieldInfos": [
                {
                  "fieldName": "OBJECTID",
                  "label": "OBJECTID",
                  "visible": true
                },
                {
                  "fieldName": "DAUID",
                  "label": "DAUID",
                  "visible": true
                },
                {
                  "fieldName": "CTUID",
                  "label": "CTUID",
                  "visible": true
                }
              ],
              "showAttachments": false
            },
            {
              "layerId": 3,
              "title": "Test",
              "fieldInfos": [
                {
                  "fieldName": "OBJECTID",
                  "label": "OBJECTID",
                  "visible": true
                },
                {
                  "fieldName": "CTUID",
                  "label": "CTUID",
                  "visible": true
                },
                {
                  "fieldName": "CTNAME",
                  "label": "CTNAME",
                  "visible": true
                }
              ],
              "showAttachments": false
            }
          ]
        },
        "imagedpi": 96,
        "disableclientcaching": false
      },
      {
        "type": "Basemap",
        "name": "DeLorme’s basemap",
        "layers": {
          "layer": [
            {
              "url": "http://services.arcgisonline.com/arcgis/rest/services/Specialty/DeLorme_World_Base_Map/MapServer",
              "isReference": false,
              "opacity": 1
            }
          ]
        }
      }
    ]
  }
}
```

It seems to be an initialization error somewhere.  I can see the infoTemplates properly being applied to the layer, and the layer being added to the map, but for some reason the new layer doesn't appear in the Legend, LayerList, or AttributeTable widgets, and mapclicks don't seem to emit any service call that I can see.  Will keep investigating.

**Comment by cmndrbensisko** [comment]
It turned out to be absolute user error on my part, Robert; One of my own enhancements was conflicting with your code.  I've got it straightened out and now Dynamic and Feature layers work beautifully.  I'm still unable to add my own Basemap, though.  Can you talk me through the two-dialog process and why the OK button may not be enabling for me?

**Comment by rscheitlin** [comment]
Sure on the second dialog there is a ServiceURL Dijit that verifies the URL that you enter and checks if the layer type is MapServer or ImageServer. This check only happen when the Dijit loses focus though. So initially the popup dialog has the ok button disable until this check is completed and if the url does not match this criteria then an error message is presented to the user. So after you enter the url and then move focus to another control the OK button should become enabled or and error displayed. Are you seeing something different?

**Comment by cmndrbensisko** [comment]
I am, but it's actually the OK button on the first Basemap Dialog (Add Basemap) that remains grayed out.  The code appears to be executing properly, but as you can see, the OK button on the Add Basemap dialog never becomes enabled.  Any thoughts on this?

image

**Comment by cmndrbensisko** [comment]
Hey Robert, I've merged up all your great GUI work to the main code base.  Feel free to give the completed widget a try to confirm that everything still works.

I added two small enhancements:

1) The WebAppBuilder returns using the default WebMap when the Local Layer Widget is disabled for the current application.
2) Layer visibility for Dynamic sublayers with visibility turned off by default appeared to be bugged within the Application itself.  An onLoad function added to Dynamic layers now tidies up the visibleLayers array to better represent each layer's default visibility, and allow proper functionality of the Layer List checkboxes.

I'll write a post for this upgrade on the GeoNet forums in the next day or so.  I look forward to continuing to upgrade the tool with you in the future.

**Comment by rscheitlin** [comment]
Adam,
   Great addition of having the widget revert back to the original web map when the widget is disabled. I have started on adding the UI for tiled layer type and will have that pull request ready soon.

   Do you have any other ideas on enhancements that you are considering? I have been contemplating about when a person adds a layer and then goes back in and removes the layer from the widget it stays on the map currently. It would probably be good to remove it from the map as well as removing it from the widget config.

**Comment by cmndrbensisko** [comment]
Hey Robert; I originally had the map performing a RemoveAllLayers() command when the settings box was exited, which forced all layers to redraw according to the most recent config.  Unfortunately, this was causing layers to drop from the LayerList in the builder, for some reason, though the App itself would work fine.  In any case, I didn't want to leave it in if it would cause confusion, but getting that functionality to work would be stellar.

One thing I found was that when Polygon Feature Layers are added to the builder, their outlines don't retain their color in the finished app, and show up as generic black borders.

Feature Layers should retain any text labelling they would otherwise have in a Dynamic Layer.  I think this can be handled much more easily using some labellinginfo object that gets passed along in 10.2 Server json, but we might need to backport that functionality for 10.0 services as well.

It would be great to be able to remove layers from dynamic services, and have the LayerList display the Dynamic Service as only containing the chosen sublayers.  I tried to make a bit of progress with this, but was unable to keep LayerList from displaying the entire service, even when sublayers were removed or constantly set to false visibility.

Otherwise, I'm happy letting the app marinate in the community for a bit.  It might be interesting getting all the unused GeoRSS and WMS stuff hooked up as addable layers too, but that falls somewhere between 'nice to have' and 'science project'.

**Comment by rscheitlin** [comment]
Adam,   Can you add me as a collaborator so I can assign myself to some new issues added to the repo? here is a link on how to do that.
https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Pull request merged**
